// Generated by CoffeeScript 1.4.0
(function() {
  var Site, console, length, method, methods;

  Site = angular.module('Site', ['ngResource']);

  Site.config(function($routeProvider, $locationProvider) {
    return $routeProvider.when('/', {
      templateUrl: 'views/home/front.html',
      controller: 'FrontCtrl'
    }).when('/home/login', {
      templateUrl: 'views/home/login.html',
      controller: 'LoginCtrl'
    }).when('/manage', {
      redirectTo: 'manage/usage'
    }).when('/manage/:page', {
      templateUrl: 'views/manage/index.html',
      controller: 'ManageCtrl'
    }).when('/not-found', {
      templateUrl: 'views/errors/not-found.html'
    }).otherwise({
      redirectTo: '/not-found'
    });
  });

  Site.controller('FrontCtrl', function($scope, Api) {
    return $scope.translateFromId = function(id) {
      return $scope.data.translated = Api.translation.get({
        id: id
      });
    };
  });

  Site.controller('ManageCtrl', function($scope, $routeParams, Api) {
    $scope.company = new Api.company();
    $scope.addCompany = function() {
      return $scope.company.$save();
    };
    $scope.users = Api.user.query();
    $scope.companies = Api.company.query();
    $scope.activePage = $routeParams.page;
    return $scope.$on('$routeChangeSuccess', function(scope, next, current) {
      return $scope.activePage = next.params.page;
    });
  });

  Site.controller('LoginCtrl', function($scope, Api) {
    return $scope.login = function() {
      return Api.auth.login($scope.data.userName, $scope.data.password);
    };
  });

  methods = ['assert', 'clear', 'count', 'debug', 'dir', 'dirxml', 'error', 'exception', 'group', 'groupCollapsed', 'groupEnd', 'info', 'log', 'markTimeline', 'profile', 'profileEnd', 'table', 'time', 'timeEnd', 'timeStamp', 'trace', 'warn'];

  length = methods.length;

  console = (window.console = window.console || {});

  while (length--) {
    method = methods[length];
    if (!console[method]) {
      console[method] = function() {};
    }
  }

  Site.value('BaseURL', 'http://localhost:55471\:55471');

  Site.factory('Api', function($http, $resource, Auth, BaseURL) {
    return {
      translation: $resource(BaseURL + '/api/translation/:id'),
      user: $resource(BaseURL + '/api/user/:id'),
      company: $resource(BaseURL + '/api/company/:id'),
      auth: Auth
    };
  });

  Site.factory('Auth', function(BaseURL) {
    return {
      login: function(userName, password) {
        return console.log(BaseURL, userName, password);
      }
    };
  });

}).call(this);
