// Generated by CoffeeScript 1.4.0
(function() {

  Site.directive('roleNav', function(Session) {
    return {
      restrict: 'A',
      link: function(scope, element, attrs) {
        var clearance, updateVisibility;
        clearance = parseInt(attrs.roleNav);
        updateVisibility = function() {
          var user;
          user = Session.user;
          if (clearance === 0) {
            return element.show();
          } else if (user != null) {
            if (clearance === -1) {
              return element.hide();
            } else if (user.Role.Id <= clearance) {
              return element.show();
            } else {
              return element.hide();
            }
          } else if (clearance === -1) {
            return element.show();
          } else {
            return element.hide();
          }
        };
        scope.$on('session:changed', function() {
          return updateVisibility();
        });
        return updateVisibility();
      }
    };
  });

}).call(this);
