// Generated by CoffeeScript 1.4.0
(function() {

  Site.directive('roleNav', function(Session) {
    return {
      restrict: 'A',
      link: function(scope, element, attrs) {
        var requiredRole, updateVisibility;
        requiredRole = parseInt(attrs.roleNav);
        updateVisibility = function() {
          if (requiredRole === 0) {
            return element.show();
          } else if (Session.isLoggedIn() && requiredRole === -1) {
            return element.hide();
          } else if (Session.isLoggedIn() && _.any(Session.user.Roles, function(role) {
            return role.Id === requiredRole;
          })) {
            return element.show();
          } else if (!Session.isLoggedIn() && requiredRole === -1) {
            return element.show();
          } else {
            return element.hide();
          }
        };
        scope.$on('session:changed', function() {
          return updateVisibility();
        });
        return updateVisibility();
      }
    };
  });

}).call(this);
