// Generated by CoffeeScript 1.4.0
(function() {

  Site.controller('NavCtrl', function($scope, Session, $location) {
    var updateScope;
    updateScope = function() {
      return $scope.data = {
        isLoggedIn: Session.isLoggedIn(),
        displayName: Session.isLoggedIn() ? Session.user.FirstName : void 0
      };
    };
    updateScope();
    $scope.$on('session:changed', updateScope);
    return $scope.logout = function() {
      Session.logout();
      return $location.path('/');
    };
  });

  Site.controller('HomeIndexCtrl', function($scope, Api) {
    return $scope.translateFromId = function(id) {
      return $scope.data.translated = Api.translation.get({
        id: id
      });
    };
  });

  Site.controller('HomeLoginCtrl', function($scope, $http, $location, Session, Api) {
    return $scope.login = function() {
      var error, success;
      success = function(response) {
        if (response.status === 200) {
          Session.login(response.data);
          return $location.path('/');
        }
      };
      error = function(response) {
        return alert('Invalid login!');
      };
      return Api.auth.login($scope.data.userName, $scope.data.password).then(success, error);
    };
  });

}).call(this);
