// Generated by CoffeeScript 1.4.0
(function() {

  Site.controller('NavCtrl', function($scope, Session, $location) {
    var updateScope;
    updateScope = function() {
      return $scope.data = {
        isAuthenticated: Session.isAuthenticated(),
        displayName: Session.isAuthenticated() ? Session.user.FirstName : void 0
      };
    };
    updateScope();
    $scope.$on('session:changed', updateScope);
    return $scope.logout = function() {
      Session.logout();
      return $location.path('/');
    };
  });

  Site.controller('HomeIndexCtrl', function($scope, Api) {
    return $scope.translateFromId = function(id) {
      return $scope.data.translated = Api.translation.get({
        id: id
      });
    };
  });

  Site.controller('HomeLoginCtrl', function($scope, $http, $location, Session, Api) {
    return $scope.login = function() {
      var error, success, token;
      token = Session.generateToken($scope.data.userName, $scope.data.password);
      success = function(response) {
        if (response.status === 200) {
          Session.login(response.data, token);
          return $location.path('/');
        }
      };
      error = function(response) {
        return alert('How about no!');
      };
      return Api.auth.validateToken(token).then(success, error);
    };
  });

}).call(this);
