// Generated by CoffeeScript 1.4.0
(function() {

  Site.controller('ManageIndexCtrl', function($scope, $routeParams, $location, Api, Utils) {
    $scope.company = new Api.company();
    $scope.user = new Api.user();
    $scope.user.Roles = [];
    $scope.addCompany = function() {
      return $scope.company.$save();
    };
    $scope.addUser = function() {
      var error, success;
      success = function() {
        return $location.path('/manage/users');
      };
      error = function(u, response) {
        alert('something bad happenede');
        return console.log(u, response);
      };
      return $scope.user.$save({}, success, error);
    };
    $scope.addRole = function(selectedRole) {
      var _ref;
      return _ref = Utils.moveElement({
        Id: parseInt(selectedRole)
      }, $scope.availableUserRoles, $scope.user.Roles), $scope.availableUserRoles = _ref[0], $scope.user.Roles = _ref[1], _ref;
    };
    $scope.removeRole = function(role) {
      var _ref;
      return _ref = Utils.moveElement(role, $scope.user.Roles, $scope.availableUserRoles), $scope.user.Roles = _ref[0], $scope.availableUserRoles = _ref[1], _ref;
    };
    $scope.removeUser = function(user) {
      return Api.user.remove({
        id: user.Id
      }, function() {
        return $scope.apply(function() {
          return $scope.users = Api.user.query();
        });
      });
    };
    $scope.users = Api.user.query();
    $scope.companies = Api.company.query();
    $scope.availableUserRoles = Api.userRole.query();
    $scope.activePage = $routeParams.page;
    return $scope.$on('$routeChangeSuccess', function(scope, next, current) {
      return $scope.activePage = next.params.page;
    });
  });

}).call(this);
