// Generated by CoffeeScript 1.4.0
(function() {

  describe('manage controller', function() {
    var $browser, $scope, ctrl;
    $scope = null;
    $browser = null;
    return ctrl = null;
  });

}).call(this);
